att_proj: cnn
attention: true
base:
- time_idx
- art
- pos
- doy_sine
- doy_cosine
bias: false
categorical_groups: {}
causal:
- weekday
- snap
- relprice
- National
- Cultural
- Sporting
clean_past: false
cov_emb: 8
cov_heads: 4
dropout: 0.3
embedding_labels:
  Cultural:
    '-': 0
    Cinco De Mayo: 1
    Cinco De Mayo-1: 2
    Cinco De Mayo-2: 3
    Cinco De Mayo-3: 4
    Cinco De Mayo-4: 5
    Cinco De Mayo-5: 6
    Easter: 7
    Easter-1: 8
    Easter-2: 9
    Easter-3: 10
    Easter-4: 11
    Easter-5: 12
    Father's day: 13
    Father's day-1: 14
    Father's day-2: 15
    Father's day-3: 16
    Father's day-4: 17
    Father's day-5: 18
    Halloween: 19
    Halloween-1: 20
    Halloween-2: 21
    Halloween-3: 22
    Halloween-4: 23
    Halloween-5: 24
    Mother's day: 25
    Mother's day-1: 26
    Mother's day-2: 27
    Mother's day-3: 28
    Mother's day-4: 29
    Mother's day-5: 30
    StPatricksDay: 31
    StPatricksDay-1: 32
    StPatricksDay-2: 33
    StPatricksDay-3: 34
    StPatricksDay-4: 35
    StPatricksDay-5: 36
    ValentinesDay: 37
    ValentinesDay-1: 38
    ValentinesDay-2: 39
    ValentinesDay-3: 40
    ValentinesDay-4: 41
    ValentinesDay-5: 42
  National:
    '-': 0
    Christmas: 1
    Christmas-1: 2
    Christmas-2: 3
    Christmas-3: 4
    Christmas-4: 5
    Christmas-5: 6
    ColumbusDay: 7
    ColumbusDay-1: 8
    ColumbusDay-2: 9
    ColumbusDay-3: 10
    ColumbusDay-4: 11
    ColumbusDay-5: 12
    IndependenceDay: 13
    IndependenceDay-1: 14
    IndependenceDay-2: 15
    IndependenceDay-3: 16
    IndependenceDay-4: 17
    IndependenceDay-5: 18
    LaborDay: 19
    LaborDay-1: 20
    LaborDay-2: 21
    LaborDay-3: 22
    LaborDay-4: 23
    LaborDay-5: 24
    MartinLutherKingDay: 25
    MartinLutherKingDay-1: 26
    MartinLutherKingDay-2: 27
    MartinLutherKingDay-3: 28
    MartinLutherKingDay-4: 29
    MartinLutherKingDay-5: 30
    MemorialDay: 31
    MemorialDay-1: 32
    MemorialDay-2: 33
    MemorialDay-3: 34
    MemorialDay-4: 35
    MemorialDay-5: 36
    NewYear: 37
    NewYear-1: 38
    NewYear-2: 39
    NewYear-3: 40
    NewYear-4: 41
    NewYear-5: 42
    PresidentsDay: 43
    PresidentsDay-1: 44
    PresidentsDay-2: 45
    PresidentsDay-3: 46
    PresidentsDay-4: 47
    PresidentsDay-5: 48
    Thanksgiving: 49
    Thanksgiving-1: 50
    Thanksgiving-2: 51
    Thanksgiving-3: 52
    Thanksgiving-4: 53
    Thanksgiving-5: 54
    VeteransDay: 55
    VeteransDay-1: 56
    VeteransDay-2: 57
    VeteransDay-3: 58
    VeteransDay-4: 59
    VeteransDay-5: 60
  Sporting:
    '-': 0
    NBAFinalsEnd: 1
    NBAFinalsEnd-1: 2
    NBAFinalsEnd-2: 3
    NBAFinalsEnd-3: 4
    NBAFinalsEnd-4: 5
    NBAFinalsEnd-5: 6
    NBAFinalsStart: 7
    NBAFinalsStart-1: 8
    NBAFinalsStart-2: 9
    NBAFinalsStart-3: 10
    NBAFinalsStart-4: 11
    NBAFinalsStart-5: 12
    SuperBowl: 13
    SuperBowl-1: 14
    SuperBowl-2: 15
    SuperBowl-3: 16
    SuperBowl-4: 17
    SuperBowl-5: 18
  art:
    FOODS_3_252: 0
    FOODS_3_586: 1
  pos:
    CA_3: 0
    TX_1: 1
    TX_2: 2
    TX_3: 3
  snap:
    '-': 0
    x: 1
  weekday:
    '0': 0
    '1': 1
    '2': 2
    '3': 3
    '4': 4
    '5': 5
    '6': 6
embedding_paddings: []
embedding_sizes:
  Cultural: !!python/tuple
  - 43
  - 8
  National: !!python/tuple
  - 61
  - 8
  Sporting: !!python/tuple
  - 19
  - 8
  art: !!python/tuple
  - 2
  - 8
  pos: !!python/tuple
  - 4
  - 8
  snap: !!python/tuple
  - 2
  - 8
  weekday: !!python/tuple
  - 7
  - 8
factor: 2
hidden_continuous_size: 4
hidden_continuous_sizes: {}
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: -1
max_encoder_length: 28
max_prediction_length: 14
monotone_constaints: {}
one_hot_not_minus_one:
- weekday
optimizer: adamw
optimizer_params: null
output_size: 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  groups:
  - time_series
  method: standard
  method_kwargs: {}
  missing_:
    center: 70.83031463623047
    scale: 23.959867477416992
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 5
          - !!python/object/apply:numpy.dtype
            args:
            - f4
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            D+lxQh+pjUI52W9CGlzNQrO4n0LPrb9B5m6LQVaGm0GuhvNBNDjIQQ==
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - &id002 !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - *id002
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 5
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAA==
          name: time_series
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 10
reduce_on_plateau_reduction: 2.0
rescale: false
share_single_variable_networks: false
static_categoricals:
- art
- pos
static_reals: []
target:
- sales
time_varying_categoricals_decoder:
- weekday
- snap
- Sporting
- Cultural
- National
time_varying_categoricals_encoder:
- weekday
- snap
- Sporting
- Cultural
- National
time_varying_reals_decoder:
- time_idx
- relprice
- doy_sine
- doy_cosine
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- relprice
- doy_sine
- doy_cosine
- relative_time_idx
- sales
weight_decay: 0.01
x_categoricals:
- art
- pos
- weekday
- snap
- Sporting
- Cultural
- National
x_reals:
- time_idx
- relprice
- doy_sine
- doy_cosine
- relative_time_idx
- sales
